### ISSUE TITLE
Small test recorded, exception in puppeteer execution

### ISSUE THREAD

**Issue by rccclr** [checkly/puppeteer-recorder#17]
Hello
What is the problem in execution?
Many thanks

![virtualbox_2018-08-27_11-49-36](https://user-images.githubusercontent.com/5550864/44653411-b32fcc00-a9bc-11e8-800f-eb387cd4e1b7.png)

**Comment by tnolet** [comment]
Hi @rccclr the element you want to click is not available in the page yet. This has to do with the asynchronicity of browser interaction and totally normal. You will have to add a `page.waitForSelector` clause before the `page.click` call. Puppeteer Recorder does not do that at this moment.

**Comment by tnolet** [comment]
Hi @rccclr I think your issue is not related to Puppeteer Recorder, but more to using Puppeteer in general. I'm sorry I can't help you with that. I would recommend seeking help here:
1. https://http://puppeteer.slack.com/ - the Slack community is quite helpful
2. https://pptr.dev - the official docs 

Also, when posting questions please provide the actual code so the issue can be reproduced. You are requesting people to now type over your code or for some reason from memory produce an answer. You will get more and quicker help when supplying a reproducible case.
